---
# tasks file for deploy_nginx_web
- block: #== for Ubuntu

   - name: inst Nginx for Ubuntu
     apt: name=nginx state=latest

   - name: Copy virtualhost config
     template: src=default.conf dest=/etc/nginx/sites-available/{{ server_name }} mode='0755'

   - name: Create symbolic link activation
     ansible.builtin.file: src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link owner=root group=root mode=0755 force=true

  when: ansible_os_family=="Debian" 

- name: Create directory for virtualhost
  ansible.builtin.file: dest=/var/www/{{ server_name }}/html/ state=directory mode='0755'

  notify: 
    - restart nginx Ubuntu
